### ISSUE TITLE
[Bug] Images url

### ISSUE THREAD

**Issue by stunslave** [Sarrus1/shavit-discord#4]
Not really a bug.. 
I would like to know if there is a different image url that works.
I'm not really keen to screen every bhop map LOL. (there's alot)

Because this gametracker url doesn't seem to. As shown in the image below.
`sm_bhop_discord_thumbnail_root_url "https://image.gametracker.com/images/maps/160x120/csgo/"`

![image](https://user-images.githubusercontent.com/47533535/122091011-a9471400-ce08-11eb-9c63-cc20267cdd5a.png)

**Comment by Sarrus1** [comment]
I don't think a better solution exists for now :/

**Comment by stunslave** [comment]
Alright kewl thanks! 
Btw it does work it's just every like 1 outa like 50 maps!
