### ISSUE TITLE
[Bug] Edit - Cant Compile Plugin

### ISSUE THREAD

**Issue by stunslave** [Sarrus1/shavit-discord#5]
No longer working with latest Shavit - https://github.com/shavitush/bhoptimer/releases/tag/v3.0.0

**Comment by Sarrus1** [comment]
Thanks for reporting this.
I'll try to fix this as soon as I can.

**Comment by stunslave** [comment]
Nvm it does work, just doesn't compile. Have to use the precompiled version.

**Compile Error:**
![image](https://user-images.githubusercontent.com/47533535/127763213-bfb1f2e2-a507-4eb0-be00-ee95181965e3.png)

**Comment by stunslave** [comment]
If using newest ripext ...

Compile Error:
![image](https://user-images.githubusercontent.com/47533535/127770540-41b50668-c2b2-4132-ad45-f27091bbc90d.png)
